--DROP TABLE
DROP TABLE IF EXISTS RDSCNFG.EXT_FILE_AUDIT;

--create table
CREATE TABLE
    RDSCNFG.EXT_FILE_AUDIT (
        ext_file_audit_sid int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
        ext_interface_cid numeric(30) NOT NULL,
        tgt_schema_name varchar(200) NOT NULL,
        tgt_table_name varchar(200) NOT NULL,
        file_process_status varchar(50) NOT NULL,
        file_process_date timestamp NOT NULL,
        file_prcsd_flag varchar(1) NOT NULL,
        merge_query varchar(65535) NULL,
        error_msg varchar(4000) NULL,
        start_time timestamp NOT NULL,
        end_time timestamp NOT NULL,
        update_query varchar(65535) NULL,
        escape_char varchar(50) NULL,
        created_date timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
        modified_date timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP
    );

ALTER TABLE RDSCNFG.EXT_FILE_AUDIT ADD CONSTRAINT XPKETL_FILE_AUDIT PRIMARY KEY (EXT_FILE_AUDIT_SID);

ALTER TABLE RDSCNFG.EXT_FILE_AUDIT ADD CONSTRAINT XFK1_EXT_FILE_AUDIT FOREIGN KEY (EXT_INTERFACE_CID) REFERENCES RDSCNFG.EXT_INTERFACE (EXT_INTERFACE_CID);

--comment on table 
COMMENT ON TABLE RDSCNFG.EXT_FILE_AUDIT IS 'This table stores the interface file audit information.';

--comment on columns
COMMENT ON COLUMN RDSCNFG.EXT_FILE_AUDIT.EXT_FILE_AUDIT_SID IS 'The unique system identifier to identify the interface file audit information.';

COMMENT ON COLUMN RDSCNFG.EXT_FILE_AUDIT.EXT_INTERFACE_CID IS 'The unique system identifier to identify the interface file information.';

COMMENT ON COLUMN RDSCNFG.EXT_FILE_AUDIT.TGT_SCHEMA_NAME IS 'The name of the Target Schema.';

COMMENT ON COLUMN RDSCNFG.EXT_FILE_AUDIT.TGT_TABLE_NAME IS 'The name of the Target Table.';

COMMENT ON COLUMN RDSCNFG.EXT_FILE_AUDIT.FILE_PROCESS_STATUS IS 'The status of the file process.';

COMMENT ON COLUMN RDSCNFG.EXT_FILE_AUDIT.FILE_PROCESS_DATE IS 'The date on which the file is processed.';

COMMENT ON COLUMN RDSCNFG.EXT_FILE_AUDIT.FILE_PRCSD_FLAG IS 'The flag to indicate the file is processed or not.';

COMMENT ON COLUMN RDSCNFG.EXT_FILE_AUDIT.MERGE_QUERY IS 'The actual queiry used to merge the data.';

COMMENT ON COLUMN RDSCNFG.EXT_FILE_AUDIT.ERROR_MSG IS 'The flag to indicate the file is processed or not.';

COMMENT ON COLUMN RDSCNFG.EXT_FILE_AUDIT.START_TIME IS 'The process start time.';

COMMENT ON COLUMN RDSCNFG.EXT_FILE_AUDIT.END_TIME IS 'The process end time.';

COMMENT ON COLUMN RDSCNFG.EXT_FILE_AUDIT.UPDATE_QUERY IS 'The actual queiry used to update the table/record.';

COMMENT ON COLUMN RDSCNFG.EXT_FILE_AUDIT.CREATED_DATE IS 'Date and time on which record get created. This shall be used on insert only.';

COMMENT ON COLUMN RDSCNFG.EXT_FILE_AUDIT.MODIFIED_DATE IS 'Date and time on which the record was modified. This will be used on each update or when the record is marked for soft delete.';

COMMENT ON COLUMN RDSCNFG.EXT_FILE_AUDIT.ESCAPE_CHAR IS 'The Escape Character.';
